<select id="county_dropdown" name="county">
	<option value="">Select a county of California</option>
	<option value="Alameda County">Alameda County</option>
	<option value="Alpine County">Alpine County</option>
	<option value="Amador County">Amador County</option>
	<option value="Butte County">Butte County</option>
	<option value="Calaveras County">Calaveras County</option>
	<option value="Colusa County">Colusa County</option>
	<option value="Contra Costa County">Contra Costa County</option>
	<option value="Del Norte County">Del Norte County</option>
	<option value="El Dorado County">El Dorado County</option>
	<option value="Fresno County">Fresno County</option>
	<option value="Glenn County">Glenn County</option>
	<option value="Humboldt County">Humboldt County</option>
	<option value="Imperial County">Imperial County</option>
	<option value="Inyo County">Inyo County</option>
	<option value="Kern County">Kern County</option>
	<option value="Kings County">Kings County</option>
	<option value="Lake County">Lake County</option>
	<option value="Lassen County">Lassen County</option>
	<option value="Los Angeles County">Los Angeles County</option>
	<option value="Madera County">Madera County</option>
	<option value="Marin County">Marin County</option>
	<option value="Mariposa County">Mariposa County</option>
	<option value="Mendocino County">Mendocino County</option>
	<option value="Merced County">Merced County</option>
	<option value="Modoc County">Modoc County</option>
	<option value="Mono County">Mono County</option>
	<option value="Monterey County">Monterey County</option>
	<option value="Napa County">Napa County</option>
	<option value="Nevada County">Nevada County</option>
	<option value="Orange County">Orange County</option>
	<option value="Placer County">Placer County</option>
	<option value="Plumas County">Plumas County</option>
	<option value="Riverside County">Riverside County</option>
	<option value="Sacramento County">Sacramento County</option>
	<option value="San Benito County">San Benito County</option>
	<option value="San Bernardino County">San Bernardino County</option>
	<option value="San Diego County">San Diego County</option>
	<option value="San Francisco County">San Francisco County</option>
	<option value="San Joaquin County">San Joaquin County</option>
	<option value="San Luis Obispo County">San Luis Obispo County</option>
	<option value="San Mateo County">San Mateo County</option>
	<option value="Santa Barbara County">Santa Barbara County</option>
	<option value="Santa Clara County">Santa Clara County</option>
	<option value="Santa Cruz County">Santa Cruz County</option>
	<option value="Shasta County">Shasta County</option>
	<option value="Sierra County">Sierra County</option>
	<option value="Siskiyou County">Siskiyou County</option>
	<option value="Solano County">Solano County</option>
	<option value="Sonoma County">Sonoma County</option>
	<option value="Stanislaus County">Stanislaus County</option>
	<option value="Sutter County">Sutter County</option>
	<option value="Tehama County">Tehama County</option>
	<option value="Trinity County">Trinity County</option>
	<option value="Tulare County">Tulare County</option>
	<option value="Tuolumne County">Tuolumne County</option>
	<option value="Ventura County">Ventura County</option>
	<option value="Yolo County">Yolo County</option>
	<option value="Yuba County">Yuba County</option>
</select>
